### ISSUE TITLE
"MAAP Login" on ADE needs to be removed.

### ISSUE THREAD

**Issue by oddes** [MAAP-Project/Community#340]
"MAAP Login" on ADE needs to be removed. 

Please see the attached screenshot. ![Screen Shot 2021-05-20 at 3.22.55 PM.png](https://images.zenhubusercontent.com/5efbaf0bd4d83e06b6d4316e/45304570-1db6-4e21-ac23-fef7f8c743a2)

Expected Functionality: Simply sign the user out of the ADE if the MAAP session expires.

**Comment by gchang** [comment]
@bsatoriu Was this feature for running Jupyterlab outside of Che? Is it needed when it's running inside the ADE?

**Comment by bsatoriu** [comment]
@gchang That came about because the user's MAAP API session can potentially expire before the end of the ADE session. The MAAP Login feature is a way to log back in this case, but the ideal solution is to simply sign the user out of the ADE if the MAAP session expires. 

This feature could be used for running Jupyterlab outside of Che, but I would suggest we hide it within the ADE, or at least change it to say "MAAP Profile", and include a menu that would show your MAAP user profile info like public ssh key and other attributes.

**Comment by marjo-luc** [comment]
The MAAP Login menu was removed some time ago. I'm unaware of any "MAAP Profile" feature within the ADE that allows users to view their profile info, but that seems like a good thing to add. 

Is it safe to close this ticket and open another one to implement the MAAP Profile feature if this feature is still of interest?

**Comment by grallewellyn** [comment]
I think it is safe to close this issue and I think a MAAP Profile feature could be of interest

**Comment by marjo-luc** [comment]
Implemented. Closing.
