### ISSUE TITLE
Cancel/Dismiss a job from the Jobs UI

### ISSUE THREAD

**Issue by rtapella** [MAAP-Project/Community#753]
**Is your feature request related to a problem? Please describe.**
Scientist has submitted a large job by accident. Would like to cancel it so that it's not gumming up the system.

**Describe the solution you'd like**
In the jobs UI I'd like to see a button or buttons to cancel a running or queued (submitted) job.
One approach would be to add it to the Job Details panel near the top (e.g. to the right of the title Job Details). Another would be to add it to the table as an option on hover or when you've selected a running or queued job. That may be more difficult because the table has minimal state as far as I can tell.

Doing it from the table would be nice at some point, so you could multi-select and cancel a bunch of stuff at once.

**Describe alternatives you've considered**
Currently you must use maap.dismissJob() to do this from python.

**Additional context**

**Comment by marjo-luc** [comment]
Notes: https://docs.google.com/document/d/1AvWHcn46P7aySN2I8ZiOwaHEEFz7Qdbct49Ad8-dWqs/edit#heading=h.749k3t9u2iu5

**Comment by rtapella** [comment]
https://github.com/MAAP-Project/Community/issues/646

**Comment by marjo-luc** [comment]
Implemented. When the user hovers over a row in the View Jobs table, an action menu containing the revoke action is displayed. Users can revoke queued or started jobs. If the job is revoked successfully, the job status will change to `job-revoked` in the UI. A toast will be displayed indicating whether or not the revoke was successful. Note that the grammatical error in the toast has been fixed in this [MAAP API PR](https://github.com/MAAP-Project/maap-api-nasa/commit/d43612c6a44edadfae6e49efc82f4a6d5094fd8e).

<img width="1955" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1gyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ecaf76a3bc696830f92f95441f913b974679a003/failed_revoke.png" alt="failed_revoke.png" />
<img width="1575" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2IyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2e0adb985f1e28e9dd5b6a95ebcebc798c777672/successful_revoke.png" alt="successful_revoke.png" />
<img width="1710" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2YyQXc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--7c060ee5cd750df453e6ace1a0c4c03af29a797e/revoke_status.png" alt="revoke_status.png" />
