### ISSUE TITLE
Presigned URLs not working in new ADE workspaces 

### ISSUE THREAD

**Issue by sujen1412** [MAAP-Project/Community#758]
From @wildintellect : "Seems like the NEW ADE get Presigned Urls is broken, the popup comes up but is empty".

![image (9).png](https://images.zenhubusercontent.com/5ee96ae63216ffad10c6273e/de35781c-c18a-4406-8212-392448d0c573)

**Comment by grallewellyn** [comment]
At ESIP this week, but I can look into this Monday!

**Comment by grallewellyn** [comment]
Is the request url for the presigned url supposed to have the variable `proxy-ticket`? 
A request for me looks like: 

https://ade.dit.maap-project.org/server27b0imtb-ws-jupyter/server-3100/jupyter-server-extension/uwm/getSignedS3Url?home_path=%2Fprojects&key=my-private-bucket%2FtestingMaapLibs.ipynb&username=anonymous&token=eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBZ21WQU1keHlxb0xzbWp5cWxjQ1huNDlCZm10TWJjZXJ0elhDdmE3WXI4In0.eyJqdGkiOiI1ZDNlYTgxYi0yMjdlLTQ2MzUtOTY5ZC1hNTA4OGQ0N2VkN2EiLCJleHAiOjE2OTAzMDkzMjgsIm5iZiI6MCwiaWF0IjoxNjkwMzA5MDI4LCJpc3MiOiJodHRwczovL2FkZS5kaXQubWFhcC1wcm9qZWN0Lm9yZy9hdXRoL3JlYWxtcy9jaGUiLCJhdWQiOiJjaGUtcHVibGljIiwic3ViIjoiOGU0ZGU1OWMtMzM3ZS00ZjM2LWE1Y2EtNzkyMmI5MmYzZTIyIiwidHlwIjoiSUQiLCJhenAiOiJjaGUtcHVibGljIiwibm9uY2UiOiJiYmZlMjUxYy1mMGFlLTQwOTQtYmFhZi05YWY2MmZlZTg4YzUiLCJhdXRoX3RpbWUiOjE2OTAzMDU1MjAsInNlc3Npb25fc3RhdGUiOiI3YWYxZWNhMi01YjUxLTQ5YzgtOTRkZS1jODZmZGQwOGRhNGIiLCJhY3IiOiIxIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsInByb3h5R3JhbnRpbmdUaWNrZXQiOiJQR1QtMTYtQlotOExVVWhSZnRBdmZNQmpSd1NVQ3R5d2N1cHBDWFV4cTk5Ui1QUzZyRmt5aFNFeW5qdkdNdVgyVHFSdi1Xd3l3MC04ODMyYTU1N2VhZWEiLCJjYXM6dXNlcm5hbWUiOiJncmFsbGV3ZWxseW4iLCJuYW1lIjoiR3JhY2UgTGxld2VsbHluIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiZ3JhbGxld2VsbHluIiwiZ2l2ZW5fbmFtZSI6IkdyYWNlIiwiZmFtaWx5X25hbWUiOiJMbGV3ZWxseW4iLCJlbWFpbCI6ImdyYWNlLmxsZXdlbGx5bkBqcGwubmFzYS5nb3YiLCJzdGF0dXMiOiJhY3RpdmUifQ.BkgIk7ma1_qSsQPhEf1tstxc7M-yOKLvdrKdpdIwCoKliMAoGg6UYDVFF2LFQJ1b2j0DWT85ZAUldVomebhECvR6DI6T1MhZgTRLZ9HI_5yQ-14rf6p4SfOzgj3YCVslr2kdSeFUWZQ8KY4fg7EpSNF1UQINKbzndv_kLDAGArQo-DIsi9JCWrk-k9IMQ3bFGbCAJoUeWPFBj_a1uAciTIsmkS33V86arN24Hkjw5vdetLhDOH3uylnJ5uuw5AYygVYEO4hlMwcV7VQBe7nnUfBN_TyR8PwH9yxsl8-YkHosjPXIv_WmG61-Hc1OT1c5C7Jc8xSxcGuUAD5W3RVsbQ&proxy-ticket=&duration=86400

Where if you see the last line, there is `proxy-ticket=&`
If I curl this url from my terminal in DIT, a line says `bash: proxy-ticket=: command not found` and the output ends with 
```
[1]-  Done                    curl https://ade.dit.maap-project.org/server27b0imtb-ws-jupyter/server-3100/jupyter-server-extension/uwm/getSignedS3Url?home_path=%2Fprojects
[5]+  Exit 127                proxy-ticket=
```
It looks like proxy-ticket is supposed to be something that begins with `PGT-` [according to maap-api-nasa](https://github.com/MAAP-Project/maap-api-nasa/blob/90a11f06bd6404bae7a9da1feb541a0469b3c34c/api/cas/cas_auth.py#L30) 
In maap-wp-plugin, it sets a [header array to proxy ticket](https://github.com/MAAP-Project/maap-wp-plugin/blob/4209ca4be41de8c1d4e753d11f2b189538ded492/views/public/profile.php#L48): `$_COOKIE['wp_maap_pgt'];`, but document.cookies in my console doesn't return this. 
 

I am also not sure if the username is supposed to be anonymous? Not sure this is the problem though because even if I change to my username, I am still getting a 404 for this request

**Comment by wildintellect** [comment]
@grallewellyn interesting, it's now broken in ade.ops.maap-project.org too. So seems you're on the right path that the API is now failing
![image](https://github.com/MAAP-Project/Community/assets/306179/aac29b2d-b82e-4185-86ef-72cb35236082)

**Comment by bsatoriu** [comment]
This is working for me using the `mas.ops.maap-project.org/root/jupyter-image/r:develop` image. 

<img width="1483" alt="Screen Shot 2023-07-26 at 3 33 31 PM" src="https://github.com/MAAP-Project/Community/assets/27687558/99e3925d-e3ef-4e76-8cce-21344cad3ecd">

@marjo-luc you had mentioned that you had fixed the missing MAAP_PGT setting in "InjectKeyHandler" with these package/ordering updates: https://github.com/MAAP-Project/jupyter-server-extension/commit/093bc116cbce145f2c196f4ef62ec0a9a9d72885. 

It looks like a similar problem may be occurring with the [Presigneds3UrlHandler](https://github.com/MAAP-Project/jupyter-server-extension/blob/bugs/presigned-url/jupyter_server_extension/handlers.py#L494). The "CHE_WORKSPACE_NAMESPACE" env variable is not present when invoking this function. Yet, it shows up in an ADE terminal using the '' image:

```
(base) root@workspaceei7q7jjtnd31i3ls:~/my-private-bucket# printenv | grep CHE_WORKSPACE_NAMESPACE
CHE_WORKSPACE_NAMESPACE=bsatoriu
```

**Comment by grallewellyn** [comment]
Thanks @bsatoriu! Are you seeing print statements from Presigneds3UrlHandler from jupyter-server-extension? If so, how? 

Also, is the problem "CHE_WORKSPACE_NAMESPACE" env variable isn't present or `proxy_ticket = self.get_argument('proxy-ticket','')` in Presigneds3UrlHandler returns nothing? Or is the problem both?

More notes on proxy ticket being missing
1. You right click to get the presigned url
2. This calls getPresignedUrl in the user-workspace-management-jupyter-extension [here](https://github.com/MAAP-Project/user-workspace-management-jupyter-extension/blob/5395734e57826cf94c1a0ba94e225d365e248b2e/src/selector.ts#L46 )
3. The getPresignedUrl function is [here](https://github.com/MAAP-Project/user-workspace-management-jupyter-extension/blob/5395734e57826cf94c1a0ba94e225d365e248b2e/src/funcs.ts#L45)
4. This tries to get the proxy-ticket like `getUrl.searchParams.append('proxy-ticket', profile.ticket);` [here](https://github.com/MAAP-Project/user-workspace-management-jupyter-extension/blob/5395734e57826cf94c1a0ba94e225d365e248b2e/src/funcs.ts#L58C5-L58C64)

If I add a print statement for `profile` and run this jupyter extension in the ADE, profile is
![Screenshot 2023-07-26 at 4.08.56 PM.png](https://images.zenhubusercontent.com/6333605b521a1e34fb21fe22/147092b0-36e1-4d45-96f5-3d1606c345e5)

**Comment by bsatoriu** [comment]
@grallewellyn you can see the print statements by following the kubernetes logs in the ADE: `kubectl logs -n {user namespace}  {workspace pod name} -c jupyter -f`. 

In my case: `kubectl logs -n bsatoriu-che    workspaceei7q7jjtnd31i3ls.ws-6f46759664-rwvzt -c jupyter -f`

To your first question, I think the problem is both. We could bypass the proxy-ticket argument by using the `MAAP_PGT` environment variable, but given that `CHE_WORKSPACE_NAMESPACE` is empty, the `MAAP_PGT` is likely empty too.

With regard to the missing client profile data: it looks like it stems from the `ade_server` variable not getting assigned correctly in our current environment (see https://github.com/MAAP-Project/user-workspace-management-jupyter-extension/blob/5395734e57826cf94c1a0ba94e225d365e248b2e/src/funcs.ts#L137).

**Comment by grallewellyn** [comment]
Sounds good for setting proxy-ticket to the `MAAP_PGT` environment variable. 

What is happening in `getUsernameToken` is `ade_server` is empty (maybe because [ade_server = environment['ade_server'];](https://github.com/MAAP-Project/user-workspace-management-jupyter-extension/blob/5395734e57826cf94c1a0ba94e225d365e248b2e/src/funcs.ts#L133) isn't being executed or executed correctly? which goes into an else statement executing `return state.fetch(profileId).then((profile) => {` and profile isn't defined so it errors out and is just returning the default profile (uname: anonymous, ticket: '')

I will look more into this, thanks!

**Comment by grallewellyn** [comment]
I am seeing the presigned url in old ops, but not new ops

I am still testing user-workspace-management-jupyter-extension to see why ade_server isn't being initialized

**Comment by grallewellyn** [comment]
@sujen1412 Is proxy-ticket still relevant in the request to get the presigned url? It is used to make this request here: https://github.com/MAAP-Project/jupyter-server-extension/blob/471b4b0eb42a59ec0284917a2f33f4e026beacdf/jupyter_server_extension/handlers.py#L558

**Comment by bsatoriu** [comment]
@grallewellyn yes, it is still required to authorize to prevent anonymous users from generating presigned urls.

**Comment by marjo-luc** [comment]
@bsatoriu on DIT as well?

**Comment by bsatoriu** [comment]
Yes
