### ISSUE TITLE
Duplicate job tag in Jobs UI 

### ISSUE THREAD

**Issue by pahbs** [MAAP-Project/Community#797]
At the `Submit` tab, after entering the `Job Tag` string it will appear duplicated in the list of jobs at the `View` tab. 

So, job tag 'test' will appear as 'testtest'

This is minor, but could be confusing.

**Comment by rtapella** [comment]
If you have a list of tags, it'll also duplicate the first tag only.

**Comment by grallewellyn** [comment]
@marjo-luc Is there a reason why the tags in the object returned by getUserJobs (ie request that looks like https://ade.dit.maap-project.org/servermcaivra0-ws-jupyter/server-3100/jupyter-server-extension/listUserJobs?username=mlucas) are sometimes an array of 2 duplicates? I went through all the tags for my algorithms and yours and Brian's (total of about 70 tags) and about half were array duplicates and there were no instances of an array with 2 different tag names 

I am thinking about adding a check in the parseJobData function to see if tags is an array, and if it is, only make the tag the first element in that array for the object returned by parseJobData. Do you see something wrong with this approach? It worked in DIT
Before:
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzYyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--fecc8ca4c7a067344b94f379c17caa0c2aa11038/Screenshot%202023-09-19%20at%2012.33.15%20PM.png)

After: 
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBbzIyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--2628a8a38f8a94d771ee71b8fe6e67b487784c48/Screenshot%202023-09-19%20at%2012.32.38%20PM.png)

**Comment by marjo-luc** [comment]
@grallewellyn Have you looked for the duplicate tags in the MAAP API?

**Comment by grallewellyn** [comment]
@marjo-luc https://api.maap-project.org/api/dps/job/grallewellyn/list Returns no results (even though I have submitted jobs in MAAP ADE OPS)

https://api.dit.maap-project.org/api/dps/job/grallewellyn/list does have tag results with duplicate tag arrays

**Comment by marjo-luc** [comment]
If the MAAP API is returning duplicate tags, I recommend you investigate the API more before considering making UI changes. Can you try submitting jobs through the MAAP API directly and through the maap-py library to see if you see the same behavior? Also, are the jobs with duplicate tags recent or older?

**Comment by grallewellyn** [comment]
@marjo-luc This is happening for both new and old jobs. 
I tried using the MAAP API but the post for https://api.maap-project.org/api/ doesn't take any arguments and gives an internal server error for https://api.maap-project.org/api/dps/job 

I agree we should avoid making UI changes, but would it be too much of a UI change to make a change to [parseJobData](https://github.com/MAAP-Project/dps-jupyter-extension/blob/main/src/utils/mapping.ts) and change the `tmpJob.tags = tmp[0][1]['tags']` to instead be inside the `if (tmp[0][1]['job']) {` and be `tmpJob.tags = tmp[0][1]['job']['tag'];`? This solves the problem and isn't as messy as checking to see if `tags` is an array or not. 
I made a notebook testing that the `tag` option would be okay to use: shared-buckets/grace.llewellyn/testingMAAPPyJupyterServerExtension.ipynb where I verified 1) tag was already string 2) equal to first element of `tags` variable 3) always existed under job 

If you don't agree with this, I can find the fix for the root level `tags` variable to make it only be returning one element, but why was it made an array in this first place? Don't want this to break anything else 

Screenshot of tmp variable in parseJobData:
<img width="553" alt="Screenshot 2023-09-26 at 11 10 14 AM" src="https://github.com/MAAP-Project/Community/assets/114033465/991f3819-2584-4c1c-a475-31a6baceaf81">

**Comment by marjo-luc** [comment]
@grallewellyn Try using the maap-py client to submit jobs. You should be able to inspect the POST request it generates to the MAAP API using the developer tools. Testing with maap-py may also help confirm whether or not tags are handled as expected in this layer.

Multiple job tags is a use case we must support. That is why the tags param is sometimes an array and sometimes not. If I remember correctly, we have to handle it this way in the dps extension because this is how maap-py returns the data in this field.

**Comment by grallewellyn** [comment]
@marjo-luc Do you mean like in a notebook run
```
maap.submitJob(identifier="test4", algo_id="dps-triage-test",version="main",username="grace.llewellyn",queue="maap-dps-worker-8gb")
``` 
?

This isn't generating a post request for some reason 

If multiple job tags is a use case we must support, then wouldn't it make sense to change dps to be getting the string `tag` variable if `tags` is always going to be an array of duplicate values? Or are they not supposed to be duplicate values and instead supposed to be multiple unique values? So dps would need to change anyway because there should be a string or comma between the unique tag values?

**Comment by marjo-luc** [comment]
@grallewellyn This is sample python code you can use to submit a job:
`import requests

url = "https://api.dit.maap-project.org/api/dps/job"

payload = "<wps:Execute\n\txmlns:wps=\"http://www.opengis.net/wps/2.0\"\n\txmlns:ows=\"http://www.opengis.net/ows/2.0\"\n\txmlns:xlink=\"http://www.w3.org/1999/xlink\"\n\txmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n       xsi:schemaLocation=\"http://www.opengis.net/wps/2.0 ../wps.xsd\" service=\"WPS\"\n       version=\"2.0.0\" response=\"document\" mode=\"sync\">\n\t<ows:Identifier>job-run-dps-test_ubuntu:main</ows:Identifier>\n\t<wps:Input id=\"queue\">\n\t\t<wps:Data>\n\t\t\t<wps:LiteralValue>maap-dps-worker-16gb</wps:LiteralValue>\n\t\t</wps:Data>\n\t</wps:Input>\n\t<wps:Input id=\"username\">\n\t\t<wps:Data>\n\t\t\t<wps:LiteralValue>mlucas</wps:LiteralValue>\n\t\t</wps:Data>\n\t</wps:Input>\n\t<wps:Input id=\"identifier\">\n\t\t<wps:Data>\n\t\t\t<wps:LiteralValue>test-dps</wps:LiteralValue>\n\t\t</wps:Data>\n\t</wps:Input>\n    <wps:Input id=\"input_file\">\n\t\t<wps:Data>\n\t\t\t<wps:LiteralValue>\"https://raw.githubusercontent.com/MAAP-Project/dps-unit-test/main/README.md\"</wps:LiteralValue>\n\t\t</wps:Data>\n\t</wps:Input>\n\t<wps:Output id=\"result\" transmission=\"value\"/>\n</wps:Execute>"
headers = {
  'Content-Type': 'text/plain'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)
`

We should be able to support multiple, unique tags. What we do depends on what hysds-core does. We should do our best to represent data that passes through our layers the same way it is represented in hysds-core to maintain consistency.

**Comment by grallewellyn** [comment]
Once I add the escape characters in the correct spots to avoid a syntax error, this gives me 
```
<Response [500]>
<!doctype html>
<html lang=en>
<title>500 Internal Server Error</title>
<h1>Internal Server Error</h1>
<p>The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.</p>
```
This is the updated payload with the escape characters:
payload = "<wps:Execute\n\txmlns:wps=\"http://www.opengis.net/wps/2.0\"\n\txmlns:ows=\"http://www.opengis.net/ows/2.0\"\n\txmlns:xlink=\"http://www.w3.org/1999/xlink\"\n\txmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n xsi:schemaLocation=\"http://www.opengis.net/wps/2.0 ../wps.xsd\" service=\"WPS\"\n version=\"2.0.0\" response=\"document\" mode=\"sync\">\n\tows:Identifierjob-run-dps-test_ubuntu:main</ows:Identifier>\n\t<wps:Input id=\"queue\">\n\t\twps:Data\n\t\t\twps:LiteralValuemaap-dps-worker-16gb</wps:LiteralValue>\n\t\t</wps:Data>\n\t</wps:Input>\n\t<wps:Input id=\"username\">\n\t\twps:Data\n\t\t\twps:LiteralValuemlucas</wps:LiteralValue>\n\t\t</wps:Data>\n\t</wps:Input>\n\t<wps:Input id=\"identifier\">\n\t\twps:Data\n\t\t\twps:LiteralValuetest-dps</wps:LiteralValue>\n\t\t</wps:Data>\n\t</wps:Input>\n <wps:Input id=\"input_file\">\n\t\twps:Data\n\t\t\twps:LiteralValue\"https://raw.githubusercontent.com/MAAP-Project/dps-unit-test/main/README.md\"</wps:LiteralValue>\n\t\t</wps:Data>\n\t</wps:Input>\n\t<wps:Output id=\"result\" transmission=\"value\"/>\n</wps:Execute>"


So the problem is we need to fix the backend to not be able to pass duplicate tags in the `tags` variable?

**Comment by grallewellyn** [comment]
Problem present in other projects using hysds, Marjorie is going to talk to some developers then update 
Still seems like maybe an option to just use the variable `jobs/tag` instead of `tags` to resolve this issue -> just then we can't support multiple tags but we don't have supporting multiple implemented yet. How would we want to do this? Separate jobs with semicolons?

**Comment by gchang** [comment]
Need to coordinate with on HySDS upstream

**Comment by gchang** [comment]
Still waiting on upstream.

**Comment by marjo-luc** [comment]
I created a ticket in hysds core for this. We'll see what they have to say.
https://hysds-core.atlassian.net/browse/HC-506

If it isn't handled soon, we can make the changes downstream in the MAAP API.

**Comment by grallewellyn** [comment]
Hysds said "feel free to submit a PR"
So we are going to make the changes in MAAP API by putting the tags variable into a set to remove duplicates

**Comment by rtapella** [comment]
So we dont' want to contribute to a fix directly in HySDS? Is that too much activation energy to dig into the codebase?

**Comment by grallewellyn** [comment]
@marjo-luc said that would take a lot of activation energy. Marjorie, do you think it is worth me trying to look into?

**Comment by marjo-luc** [comment]
I don't think we can justify the effort from MAAP's perspective. HySDS is a complex system and we don't even know what the root cause of the issue is. Also of note, HySDS itself applies a workaround to this issue in at least one of its services rather than addressing the root cause.

**Comment by rtapella** [comment]
Sounds good to me

**Comment by grallewellyn** [comment]
Discussion 1/18:
- can we support multiple tags? What happens if user submits with comma separated list? Right now it just takes the first element of the list. What do want to happen? 
        - Right now if you try to submit a job with a tag like "testing, test, tested" or "testing,test,tested", only testing will be the tag
- we want to just put into a Set to remove duplicates.
