### ISSUE TITLE
Upgrade to JupyterLab 4

### ISSUE THREAD

**Issue by marjo-luc** [MAAP-Project/Community#957]
https://github.com/jupyterlab/jupyterlab/issues/15921
https://jupyterlab.readthedocs.io/en/latest/getting_started/lifecycle.html

Jupyterlab 4 improvements:
https://blog.jupyter.org/jupyterlab-4-0-is-here-388d05e03442

Tagging everyone for visibility as this may affect most subsystems.

**Comment by grallewellyn** [comment]
Things to consider about Jupyterlab4 upgrade that we have talked about in meetings:
- miniconda has caused problems when @anilnatha tried to upgrade it before (and I also experienced some trouble changing the miniconda version for the base images). Sujen said that we don't need to stick with miniconda

**Comment by sujen1412** [comment]
Do we want to create a v4.0.0 milestone ? Maybe leave the end date open once we talk with the team about planning what to include in first v4 release.

**Comment by grallewellyn** [comment]
Sounds good to me!

**Comment by anilnatha** [comment]
Yup, I'm good with that.

**Comment by anilnatha** [comment]
@sujen1412 Just a thought, rather than a milestone, how about a JupyterLab 4 Upgrade Epic? We can then track subtasks related to that epic.

Reason being the milestone is tracking a versioned release with our next potentially being a major release due to breaking changes.

So our next milestone may be 4.X.Y, and in that release would be the jupyterlab epic and any other tickets we _also_ address in that time.

**Comment by marjo-luc** [comment]
maap-workspaces has been updated to build the jupyterlab4 images.

Sample jlab4 workspace image:
`mas.dit.maap-project.org/root/maap-workspaces/jupyterlab/vanilla:develop`

**Comment by marjo-luc** [comment]
this was completed. closing out.
